%YAML:1.0 # need to specify the file type at the top!

imu:
  accel_noise: 0.002186841816246753       # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accel_bias:  0.0003813200687038481      # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyro_noise:  0.0003457560277163437      # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyro_bias:   1.2359539694598483e-05     # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  topic: "/imu/data"
